package tp.bigdata.schema;

/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2018-10-2")
public class PageViewEdge implements org.apache.thrift.TBase<PageViewEdge, PageViewEdge._Fields>, java.io.Serializable, Cloneable, Comparable<PageViewEdge> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("PageViewEdge");

  private static final org.apache.thrift.protocol.TField USER_FIELD_DESC = new org.apache.thrift.protocol.TField("user", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField PAGE_FIELD_DESC = new org.apache.thrift.protocol.TField("page", org.apache.thrift.protocol.TType.STRUCT, (short)2);
  private static final org.apache.thrift.protocol.TField DATE_VIEW_FIELD_DESC = new org.apache.thrift.protocol.TField("date_view", org.apache.thrift.protocol.TType.STRING, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new PageViewEdgeStandardSchemeFactory());
    schemes.put(TupleScheme.class, new PageViewEdgeTupleSchemeFactory());
  }

  private User user; // required
  private Page page; // required
  private String date_view; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    USER((short)1, "user"),
    PAGE((short)2, "page"),
    DATE_VIEW((short)3, "date_view");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // USER
          return USER;
        case 2: // PAGE
          return PAGE;
        case 3: // DATE_VIEW
          return DATE_VIEW;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.USER, new org.apache.thrift.meta_data.FieldMetaData("user", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, User.class)));
    tmpMap.put(_Fields.PAGE, new org.apache.thrift.meta_data.FieldMetaData("page", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Page.class)));
    tmpMap.put(_Fields.DATE_VIEW, new org.apache.thrift.meta_data.FieldMetaData("date_view", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(PageViewEdge.class, metaDataMap);
  }

  public PageViewEdge() {
  }

  public PageViewEdge(
    User user,
    Page page,
    String date_view)
  {
    this();
    this.user = user;
    this.page = page;
    this.date_view = date_view;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public PageViewEdge(PageViewEdge other) {
    if (other.is_set_user()) {
      this.user = new User(other.user);
    }
    if (other.is_set_page()) {
      this.page = new Page(other.page);
    }
    if (other.is_set_date_view()) {
      this.date_view = other.date_view;
    }
  }

  public PageViewEdge deepCopy() {
    return new PageViewEdge(this);
  }

  @Override
  public void clear() {
    this.user = null;
    this.page = null;
    this.date_view = null;
  }

  public User get_user() {
    return this.user;
  }

  public void set_user(User user) {
    this.user = user;
  }

  public void unset_user() {
    this.user = null;
  }

  /** Returns true if field user is set (has been assigned a value) and false otherwise */
  public boolean is_set_user() {
    return this.user != null;
  }

  public void set_user_isSet(boolean value) {
    if (!value) {
      this.user = null;
    }
  }

  public Page get_page() {
    return this.page;
  }

  public void set_page(Page page) {
    this.page = page;
  }

  public void unset_page() {
    this.page = null;
  }

  /** Returns true if field page is set (has been assigned a value) and false otherwise */
  public boolean is_set_page() {
    return this.page != null;
  }

  public void set_page_isSet(boolean value) {
    if (!value) {
      this.page = null;
    }
  }

  public String get_date_view() {
    return this.date_view;
  }

  public void set_date_view(String date_view) {
    this.date_view = date_view;
  }

  public void unset_date_view() {
    this.date_view = null;
  }

  /** Returns true if field date_view is set (has been assigned a value) and false otherwise */
  public boolean is_set_date_view() {
    return this.date_view != null;
  }

  public void set_date_view_isSet(boolean value) {
    if (!value) {
      this.date_view = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case USER:
      if (value == null) {
        unset_user();
      } else {
        set_user((User)value);
      }
      break;

    case PAGE:
      if (value == null) {
        unset_page();
      } else {
        set_page((Page)value);
      }
      break;

    case DATE_VIEW:
      if (value == null) {
        unset_date_view();
      } else {
        set_date_view((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case USER:
      return get_user();

    case PAGE:
      return get_page();

    case DATE_VIEW:
      return get_date_view();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case USER:
      return is_set_user();
    case PAGE:
      return is_set_page();
    case DATE_VIEW:
      return is_set_date_view();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof PageViewEdge)
      return this.equals((PageViewEdge)that);
    return false;
  }

  public boolean equals(PageViewEdge that) {
    if (that == null)
      return false;

    boolean this_present_user = true && this.is_set_user();
    boolean that_present_user = true && that.is_set_user();
    if (this_present_user || that_present_user) {
      if (!(this_present_user && that_present_user))
        return false;
      if (!this.user.equals(that.user))
        return false;
    }

    boolean this_present_page = true && this.is_set_page();
    boolean that_present_page = true && that.is_set_page();
    if (this_present_page || that_present_page) {
      if (!(this_present_page && that_present_page))
        return false;
      if (!this.page.equals(that.page))
        return false;
    }

    boolean this_present_date_view = true && this.is_set_date_view();
    boolean that_present_date_view = true && that.is_set_date_view();
    if (this_present_date_view || that_present_date_view) {
      if (!(this_present_date_view && that_present_date_view))
        return false;
      if (!this.date_view.equals(that.date_view))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_user = true && (is_set_user());
    list.add(present_user);
    if (present_user)
      list.add(user);

    boolean present_page = true && (is_set_page());
    list.add(present_page);
    if (present_page)
      list.add(page);

    boolean present_date_view = true && (is_set_date_view());
    list.add(present_date_view);
    if (present_date_view)
      list.add(date_view);

    return list.hashCode();
  }

  @Override
  public int compareTo(PageViewEdge other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(is_set_user()).compareTo(other.is_set_user());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (is_set_user()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.user, other.user);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(is_set_page()).compareTo(other.is_set_page());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (is_set_page()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.page, other.page);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(is_set_date_view()).compareTo(other.is_set_date_view());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (is_set_date_view()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.date_view, other.date_view);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("PageViewEdge(");
    boolean first = true;

    sb.append("user:");
    if (this.user == null) {
      sb.append("null");
    } else {
      sb.append(this.user);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("page:");
    if (this.page == null) {
      sb.append("null");
    } else {
      sb.append(this.page);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("date_view:");
    if (this.date_view == null) {
      sb.append("null");
    } else {
      sb.append(this.date_view);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (!is_set_user()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'user' is unset! Struct:" + toString());
    }

    if (!is_set_page()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'page' is unset! Struct:" + toString());
    }

    if (!is_set_date_view()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'date_view' is unset! Struct:" + toString());
    }

    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class PageViewEdgeStandardSchemeFactory implements SchemeFactory {
    public PageViewEdgeStandardScheme getScheme() {
      return new PageViewEdgeStandardScheme();
    }
  }

  private static class PageViewEdgeStandardScheme extends StandardScheme<PageViewEdge> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, PageViewEdge struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // USER
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.user = new User();
              struct.user.read(iprot);
              struct.set_user_isSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PAGE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.page = new Page();
              struct.page.read(iprot);
              struct.set_page_isSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // DATE_VIEW
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.date_view = iprot.readString();
              struct.set_date_view_isSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, PageViewEdge struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.user != null) {
        oprot.writeFieldBegin(USER_FIELD_DESC);
        struct.user.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.page != null) {
        oprot.writeFieldBegin(PAGE_FIELD_DESC);
        struct.page.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.date_view != null) {
        oprot.writeFieldBegin(DATE_VIEW_FIELD_DESC);
        oprot.writeString(struct.date_view);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class PageViewEdgeTupleSchemeFactory implements SchemeFactory {
    public PageViewEdgeTupleScheme getScheme() {
      return new PageViewEdgeTupleScheme();
    }
  }

  private static class PageViewEdgeTupleScheme extends TupleScheme<PageViewEdge> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, PageViewEdge struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      struct.user.write(oprot);
      struct.page.write(oprot);
      oprot.writeString(struct.date_view);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, PageViewEdge struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.user = new User();
      struct.user.read(iprot);
      struct.set_user_isSet(true);
      struct.page = new Page();
      struct.page.read(iprot);
      struct.set_page_isSet(true);
      struct.date_view = iprot.readString();
      struct.set_date_view_isSet(true);
    }
  }

}

