package tp.bigdata.schema;

/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
public class User extends org.apache.thrift.TUnion<User, User._Fields> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("User");
  private static final org.apache.thrift.protocol.TField USER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("user_id", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField USERNAME_FIELD_DESC = new org.apache.thrift.protocol.TField("username", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("name", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField EMAIL_FIELD_DESC = new org.apache.thrift.protocol.TField("email", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField USER_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("user_type", org.apache.thrift.protocol.TType.STRING, (short)5);
  private static final org.apache.thrift.protocol.TField ADDRESS_FIELD_DESC = new org.apache.thrift.protocol.TField("address", org.apache.thrift.protocol.TType.STRING, (short)6);
  private static final org.apache.thrift.protocol.TField BIRTHDAY_FIELD_DESC = new org.apache.thrift.protocol.TField("birthday", org.apache.thrift.protocol.TType.STRING, (short)7);
  private static final org.apache.thrift.protocol.TField PHONE_FIELD_DESC = new org.apache.thrift.protocol.TField("phone", org.apache.thrift.protocol.TType.STRING, (short)8);

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    USER_ID((short)1, "user_id"),
    USERNAME((short)2, "username"),
    NAME((short)3, "name"),
    EMAIL((short)4, "email"),
    USER_TYPE((short)5, "user_type"),
    ADDRESS((short)6, "address"),
    BIRTHDAY((short)7, "birthday"),
    PHONE((short)8, "phone");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // USER_ID
          return USER_ID;
        case 2: // USERNAME
          return USERNAME;
        case 3: // NAME
          return NAME;
        case 4: // EMAIL
          return EMAIL;
        case 5: // USER_TYPE
          return USER_TYPE;
        case 6: // ADDRESS
          return ADDRESS;
        case 7: // BIRTHDAY
          return BIRTHDAY;
        case 8: // PHONE
          return PHONE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.USER_ID, new org.apache.thrift.meta_data.FieldMetaData("user_id", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.USERNAME, new org.apache.thrift.meta_data.FieldMetaData("username", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.NAME, new org.apache.thrift.meta_data.FieldMetaData("name", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.EMAIL, new org.apache.thrift.meta_data.FieldMetaData("email", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.USER_TYPE, new org.apache.thrift.meta_data.FieldMetaData("user_type", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ADDRESS, new org.apache.thrift.meta_data.FieldMetaData("address", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.BIRTHDAY, new org.apache.thrift.meta_data.FieldMetaData("birthday", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PHONE, new org.apache.thrift.meta_data.FieldMetaData("phone", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(User.class, metaDataMap);
  }

  public User() {
    super();
  }

  public User(_Fields setField, Object value) {
    super(setField, value);
  }

  public User(User other) {
    super(other);
  }
  public User deepCopy() {
    return new User(this);
  }

  public static User user_id(long value) {
    User x = new User();
    x.set_user_id(value);
    return x;
  }

  public static User username(String value) {
    User x = new User();
    x.set_username(value);
    return x;
  }

  public static User name(String value) {
    User x = new User();
    x.set_name(value);
    return x;
  }

  public static User email(String value) {
    User x = new User();
    x.set_email(value);
    return x;
  }

  public static User user_type(String value) {
    User x = new User();
    x.set_user_type(value);
    return x;
  }

  public static User address(String value) {
    User x = new User();
    x.set_address(value);
    return x;
  }

  public static User birthday(String value) {
    User x = new User();
    x.set_birthday(value);
    return x;
  }

  public static User phone(String value) {
    User x = new User();
    x.set_phone(value);
    return x;
  }


  @Override
  protected void checkType(_Fields setField, Object value) throws ClassCastException {
    switch (setField) {
      case USER_ID:
        if (value instanceof Long) {
          break;
        }
        throw new ClassCastException("Was expecting value of type Long for field 'user_id', but got " + value.getClass().getSimpleName());
      case USERNAME:
        if (value instanceof String) {
          break;
        }
        throw new ClassCastException("Was expecting value of type String for field 'username', but got " + value.getClass().getSimpleName());
      case NAME:
        if (value instanceof String) {
          break;
        }
        throw new ClassCastException("Was expecting value of type String for field 'name', but got " + value.getClass().getSimpleName());
      case EMAIL:
        if (value instanceof String) {
          break;
        }
        throw new ClassCastException("Was expecting value of type String for field 'email', but got " + value.getClass().getSimpleName());
      case USER_TYPE:
        if (value instanceof String) {
          break;
        }
        throw new ClassCastException("Was expecting value of type String for field 'user_type', but got " + value.getClass().getSimpleName());
      case ADDRESS:
        if (value instanceof String) {
          break;
        }
        throw new ClassCastException("Was expecting value of type String for field 'address', but got " + value.getClass().getSimpleName());
      case BIRTHDAY:
        if (value instanceof String) {
          break;
        }
        throw new ClassCastException("Was expecting value of type String for field 'birthday', but got " + value.getClass().getSimpleName());
      case PHONE:
        if (value instanceof String) {
          break;
        }
        throw new ClassCastException("Was expecting value of type String for field 'phone', but got " + value.getClass().getSimpleName());
      default:
        throw new IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected Object standardSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TField field) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(field.id);
    if (setField != null) {
      switch (setField) {
        case USER_ID:
          if (field.type == USER_ID_FIELD_DESC.type) {
            Long user_id;
            user_id = iprot.readI64();
            return user_id;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case USERNAME:
          if (field.type == USERNAME_FIELD_DESC.type) {
            String username;
            username = iprot.readString();
            return username;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case NAME:
          if (field.type == NAME_FIELD_DESC.type) {
            String name;
            name = iprot.readString();
            return name;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case EMAIL:
          if (field.type == EMAIL_FIELD_DESC.type) {
            String email;
            email = iprot.readString();
            return email;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case USER_TYPE:
          if (field.type == USER_TYPE_FIELD_DESC.type) {
            String user_type;
            user_type = iprot.readString();
            return user_type;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case ADDRESS:
          if (field.type == ADDRESS_FIELD_DESC.type) {
            String address;
            address = iprot.readString();
            return address;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case BIRTHDAY:
          if (field.type == BIRTHDAY_FIELD_DESC.type) {
            String birthday;
            birthday = iprot.readString();
            return birthday;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case PHONE:
          if (field.type == PHONE_FIELD_DESC.type) {
            String phone;
            phone = iprot.readString();
            return phone;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        default:
          throw new IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
      return null;
    }
  }

  @Override
  protected void standardSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case USER_ID:
        Long user_id = (Long)value_;
        oprot.writeI64(user_id);
        return;
      case USERNAME:
        String username = (String)value_;
        oprot.writeString(username);
        return;
      case NAME:
        String name = (String)value_;
        oprot.writeString(name);
        return;
      case EMAIL:
        String email = (String)value_;
        oprot.writeString(email);
        return;
      case USER_TYPE:
        String user_type = (String)value_;
        oprot.writeString(user_type);
        return;
      case ADDRESS:
        String address = (String)value_;
        oprot.writeString(address);
        return;
      case BIRTHDAY:
        String birthday = (String)value_;
        oprot.writeString(birthday);
        return;
      case PHONE:
        String phone = (String)value_;
        oprot.writeString(phone);
        return;
      default:
        throw new IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected Object tupleSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, short fieldID) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(fieldID);
    if (setField != null) {
      switch (setField) {
        case USER_ID:
          Long user_id;
          user_id = iprot.readI64();
          return user_id;
        case USERNAME:
          String username;
          username = iprot.readString();
          return username;
        case NAME:
          String name;
          name = iprot.readString();
          return name;
        case EMAIL:
          String email;
          email = iprot.readString();
          return email;
        case USER_TYPE:
          String user_type;
          user_type = iprot.readString();
          return user_type;
        case ADDRESS:
          String address;
          address = iprot.readString();
          return address;
        case BIRTHDAY:
          String birthday;
          birthday = iprot.readString();
          return birthday;
        case PHONE:
          String phone;
          phone = iprot.readString();
          return phone;
        default:
          throw new IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      throw new TProtocolException("Couldn't find a field with field id " + fieldID);
    }
  }

  @Override
  protected void tupleSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case USER_ID:
        Long user_id = (Long)value_;
        oprot.writeI64(user_id);
        return;
      case USERNAME:
        String username = (String)value_;
        oprot.writeString(username);
        return;
      case NAME:
        String name = (String)value_;
        oprot.writeString(name);
        return;
      case EMAIL:
        String email = (String)value_;
        oprot.writeString(email);
        return;
      case USER_TYPE:
        String user_type = (String)value_;
        oprot.writeString(user_type);
        return;
      case ADDRESS:
        String address = (String)value_;
        oprot.writeString(address);
        return;
      case BIRTHDAY:
        String birthday = (String)value_;
        oprot.writeString(birthday);
        return;
      case PHONE:
        String phone = (String)value_;
        oprot.writeString(phone);
        return;
      default:
        throw new IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TField getFieldDesc(_Fields setField) {
    switch (setField) {
      case USER_ID:
        return USER_ID_FIELD_DESC;
      case USERNAME:
        return USERNAME_FIELD_DESC;
      case NAME:
        return NAME_FIELD_DESC;
      case EMAIL:
        return EMAIL_FIELD_DESC;
      case USER_TYPE:
        return USER_TYPE_FIELD_DESC;
      case ADDRESS:
        return ADDRESS_FIELD_DESC;
      case BIRTHDAY:
        return BIRTHDAY_FIELD_DESC;
      case PHONE:
        return PHONE_FIELD_DESC;
      default:
        throw new IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TStruct getStructDesc() {
    return STRUCT_DESC;
  }

  @Override
  protected _Fields enumForId(short id) {
    return _Fields.findByThriftIdOrThrow(id);
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }


  public long get_user_id() {
    if (getSetField() == _Fields.USER_ID) {
      return (Long)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'user_id' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void set_user_id(long value) {
    setField_ = _Fields.USER_ID;
    value_ = value;
  }

  public String get_username() {
    if (getSetField() == _Fields.USERNAME) {
      return (String)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'username' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void set_username(String value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.USERNAME;
    value_ = value;
  }

  public String get_name() {
    if (getSetField() == _Fields.NAME) {
      return (String)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'name' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void set_name(String value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.NAME;
    value_ = value;
  }

  public String get_email() {
    if (getSetField() == _Fields.EMAIL) {
      return (String)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'email' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void set_email(String value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.EMAIL;
    value_ = value;
  }

  public String get_user_type() {
    if (getSetField() == _Fields.USER_TYPE) {
      return (String)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'user_type' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void set_user_type(String value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.USER_TYPE;
    value_ = value;
  }

  public String get_address() {
    if (getSetField() == _Fields.ADDRESS) {
      return (String)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'address' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void set_address(String value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.ADDRESS;
    value_ = value;
  }

  public String get_birthday() {
    if (getSetField() == _Fields.BIRTHDAY) {
      return (String)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'birthday' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void set_birthday(String value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.BIRTHDAY;
    value_ = value;
  }

  public String get_phone() {
    if (getSetField() == _Fields.PHONE) {
      return (String)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'phone' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void set_phone(String value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.PHONE;
    value_ = value;
  }

  public boolean is_set_user_id() {
    return setField_ == _Fields.USER_ID;
  }


  public boolean is_set_username() {
    return setField_ == _Fields.USERNAME;
  }


  public boolean is_set_name() {
    return setField_ == _Fields.NAME;
  }


  public boolean is_set_email() {
    return setField_ == _Fields.EMAIL;
  }


  public boolean is_set_user_type() {
    return setField_ == _Fields.USER_TYPE;
  }


  public boolean is_set_address() {
    return setField_ == _Fields.ADDRESS;
  }


  public boolean is_set_birthday() {
    return setField_ == _Fields.BIRTHDAY;
  }


  public boolean is_set_phone() {
    return setField_ == _Fields.PHONE;
  }


  public boolean equals(Object other) {
    if (other instanceof User) {
      return equals((User)other);
    } else {
      return false;
    }
  }

  public boolean equals(User other) {
    return other != null && getSetField() == other.getSetField() && getFieldValue().equals(other.getFieldValue());
  }

  @Override
  public int compareTo(User other) {
    int lastComparison = org.apache.thrift.TBaseHelper.compareTo(getSetField(), other.getSetField());
    if (lastComparison == 0) {
      return org.apache.thrift.TBaseHelper.compareTo(getFieldValue(), other.getFieldValue());
    }
    return lastComparison;
  }


  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();
    list.add(this.getClass().getName());
    org.apache.thrift.TFieldIdEnum setField = getSetField();
    if (setField != null) {
      list.add(setField.getThriftFieldId());
      Object value = getFieldValue();
      if (value instanceof org.apache.thrift.TEnum) {
        list.add(((org.apache.thrift.TEnum)getFieldValue()).getValue());
      } else {
        list.add(value);
      }
    }
    return list.hashCode();
  }
  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


}
