/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package tp.bigdata.schema;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
public class DataUnit extends org.apache.thrift.TUnion<DataUnit, DataUnit._Fields> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("DataUnit");
  private static final org.apache.thrift.protocol.TField USER_PROPERTY_FIELD_DESC = new org.apache.thrift.protocol.TField("userProperty", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField PAGE_PROPERTY_FIELD_DESC = new org.apache.thrift.protocol.TField("pageProperty", org.apache.thrift.protocol.TType.STRUCT, (short)2);
  private static final org.apache.thrift.protocol.TField PRODUCT_PROPERTY_FIELD_DESC = new org.apache.thrift.protocol.TField("productProperty", org.apache.thrift.protocol.TType.STRUCT, (short)3);
  private static final org.apache.thrift.protocol.TField FACTS_EDGE_FIELD_DESC = new org.apache.thrift.protocol.TField("factsEdge", org.apache.thrift.protocol.TType.STRUCT, (short)4);

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    USER_PROPERTY((short)1, "userProperty"),
    PAGE_PROPERTY((short)2, "pageProperty"),
    PRODUCT_PROPERTY((short)3, "productProperty"),
    FACTS_EDGE((short)4, "factsEdge");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // USER_PROPERTY
          return USER_PROPERTY;
        case 2: // PAGE_PROPERTY
          return PAGE_PROPERTY;
        case 3: // PRODUCT_PROPERTY
          return PRODUCT_PROPERTY;
        case 4: // FACTS_EDGE
          return FACTS_EDGE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.USER_PROPERTY, new org.apache.thrift.meta_data.FieldMetaData("userProperty", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, UserProperty.class)));
    tmpMap.put(_Fields.PAGE_PROPERTY, new org.apache.thrift.meta_data.FieldMetaData("pageProperty", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, PageProperty.class)));
    tmpMap.put(_Fields.PRODUCT_PROPERTY, new org.apache.thrift.meta_data.FieldMetaData("productProperty", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ProductProperty.class)));
    tmpMap.put(_Fields.FACTS_EDGE, new org.apache.thrift.meta_data.FieldMetaData("factsEdge", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, FactsEdge.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(DataUnit.class, metaDataMap);
  }

  public DataUnit() {
    super();
  }

  public DataUnit(_Fields setField, Object value) {
    super(setField, value);
  }

  public DataUnit(DataUnit other) {
    super(other);
  }
  public DataUnit deepCopy() {
    return new DataUnit(this);
  }

  public static DataUnit userProperty(UserProperty value) {
    DataUnit x = new DataUnit();
    x.set_userProperty(value);
    return x;
  }

  public static DataUnit pageProperty(PageProperty value) {
    DataUnit x = new DataUnit();
    x.set_pageProperty(value);
    return x;
  }

  public static DataUnit productProperty(ProductProperty value) {
    DataUnit x = new DataUnit();
    x.set_productProperty(value);
    return x;
  }

  public static DataUnit factsEdge(FactsEdge value) {
    DataUnit x = new DataUnit();
    x.set_factsEdge(value);
    return x;
  }


  @Override
  protected void checkType(_Fields setField, Object value) throws ClassCastException {
    switch (setField) {
      case USER_PROPERTY:
        if (value instanceof UserProperty) {
          break;
        }
        throw new ClassCastException("Was expecting value of type UserProperty for field 'userProperty', but got " + value.getClass().getSimpleName());
      case PAGE_PROPERTY:
        if (value instanceof PageProperty) {
          break;
        }
        throw new ClassCastException("Was expecting value of type PageProperty for field 'pageProperty', but got " + value.getClass().getSimpleName());
      case PRODUCT_PROPERTY:
        if (value instanceof ProductProperty) {
          break;
        }
        throw new ClassCastException("Was expecting value of type ProductProperty for field 'productProperty', but got " + value.getClass().getSimpleName());
      case FACTS_EDGE:
        if (value instanceof FactsEdge) {
          break;
        }
        throw new ClassCastException("Was expecting value of type FactsEdge for field 'factsEdge', but got " + value.getClass().getSimpleName());
      default:
        throw new IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected Object standardSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TField field) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(field.id);
    if (setField != null) {
      switch (setField) {
        case USER_PROPERTY:
          if (field.type == USER_PROPERTY_FIELD_DESC.type) {
            UserProperty userProperty;
            userProperty = new UserProperty();
            userProperty.read(iprot);
            return userProperty;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case PAGE_PROPERTY:
          if (field.type == PAGE_PROPERTY_FIELD_DESC.type) {
            PageProperty pageProperty;
            pageProperty = new PageProperty();
            pageProperty.read(iprot);
            return pageProperty;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case PRODUCT_PROPERTY:
          if (field.type == PRODUCT_PROPERTY_FIELD_DESC.type) {
            ProductProperty productProperty;
            productProperty = new ProductProperty();
            productProperty.read(iprot);
            return productProperty;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case FACTS_EDGE:
          if (field.type == FACTS_EDGE_FIELD_DESC.type) {
            FactsEdge factsEdge;
            factsEdge = new FactsEdge();
            factsEdge.read(iprot);
            return factsEdge;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        default:
          throw new IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
      return null;
    }
  }

  @Override
  protected void standardSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case USER_PROPERTY:
        UserProperty userProperty = (UserProperty)value_;
        userProperty.write(oprot);
        return;
      case PAGE_PROPERTY:
        PageProperty pageProperty = (PageProperty)value_;
        pageProperty.write(oprot);
        return;
      case PRODUCT_PROPERTY:
        ProductProperty productProperty = (ProductProperty)value_;
        productProperty.write(oprot);
        return;
      case FACTS_EDGE:
        FactsEdge factsEdge = (FactsEdge)value_;
        factsEdge.write(oprot);
        return;
      default:
        throw new IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected Object tupleSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, short fieldID) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(fieldID);
    if (setField != null) {
      switch (setField) {
        case USER_PROPERTY:
          UserProperty userProperty;
          userProperty = new UserProperty();
          userProperty.read(iprot);
          return userProperty;
        case PAGE_PROPERTY:
          PageProperty pageProperty;
          pageProperty = new PageProperty();
          pageProperty.read(iprot);
          return pageProperty;
        case PRODUCT_PROPERTY:
          ProductProperty productProperty;
          productProperty = new ProductProperty();
          productProperty.read(iprot);
          return productProperty;
        case FACTS_EDGE:
          FactsEdge factsEdge;
          factsEdge = new FactsEdge();
          factsEdge.read(iprot);
          return factsEdge;
        default:
          throw new IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      throw new TProtocolException("Couldn't find a field with field id " + fieldID);
    }
  }

  @Override
  protected void tupleSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case USER_PROPERTY:
        UserProperty userProperty = (UserProperty)value_;
        userProperty.write(oprot);
        return;
      case PAGE_PROPERTY:
        PageProperty pageProperty = (PageProperty)value_;
        pageProperty.write(oprot);
        return;
      case PRODUCT_PROPERTY:
        ProductProperty productProperty = (ProductProperty)value_;
        productProperty.write(oprot);
        return;
      case FACTS_EDGE:
        FactsEdge factsEdge = (FactsEdge)value_;
        factsEdge.write(oprot);
        return;
      default:
        throw new IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TField getFieldDesc(_Fields setField) {
    switch (setField) {
      case USER_PROPERTY:
        return USER_PROPERTY_FIELD_DESC;
      case PAGE_PROPERTY:
        return PAGE_PROPERTY_FIELD_DESC;
      case PRODUCT_PROPERTY:
        return PRODUCT_PROPERTY_FIELD_DESC;
      case FACTS_EDGE:
        return FACTS_EDGE_FIELD_DESC;
      default:
        throw new IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TStruct getStructDesc() {
    return STRUCT_DESC;
  }

  @Override
  protected _Fields enumForId(short id) {
    return _Fields.findByThriftIdOrThrow(id);
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }


  public UserProperty get_userProperty() {
    if (getSetField() == _Fields.USER_PROPERTY) {
      return (UserProperty)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'userProperty' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void set_userProperty(UserProperty value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.USER_PROPERTY;
    value_ = value;
  }

  public PageProperty get_pageProperty() {
    if (getSetField() == _Fields.PAGE_PROPERTY) {
      return (PageProperty)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'pageProperty' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void set_pageProperty(PageProperty value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.PAGE_PROPERTY;
    value_ = value;
  }

  public ProductProperty get_productProperty() {
    if (getSetField() == _Fields.PRODUCT_PROPERTY) {
      return (ProductProperty)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'productProperty' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void set_productProperty(ProductProperty value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.PRODUCT_PROPERTY;
    value_ = value;
  }

  public FactsEdge get_factsEdge() {
    if (getSetField() == _Fields.FACTS_EDGE) {
      return (FactsEdge)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'factsEdge' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void set_factsEdge(FactsEdge value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.FACTS_EDGE;
    value_ = value;
  }

  public boolean is_set_userProperty() {
    return setField_ == _Fields.USER_PROPERTY;
  }


  public boolean is_set_pageProperty() {
    return setField_ == _Fields.PAGE_PROPERTY;
  }


  public boolean is_set_productProperty() {
    return setField_ == _Fields.PRODUCT_PROPERTY;
  }


  public boolean is_set_factsEdge() {
    return setField_ == _Fields.FACTS_EDGE;
  }


  public boolean equals(Object other) {
    if (other instanceof DataUnit) {
      return equals((DataUnit)other);
    } else {
      return false;
    }
  }

  public boolean equals(DataUnit other) {
    return other != null && getSetField() == other.getSetField() && getFieldValue().equals(other.getFieldValue());
  }

  @Override
  public int compareTo(DataUnit other) {
    int lastComparison = org.apache.thrift.TBaseHelper.compareTo(getSetField(), other.getSetField());
    if (lastComparison == 0) {
      return org.apache.thrift.TBaseHelper.compareTo(getFieldValue(), other.getFieldValue());
    }
    return lastComparison;
  }


  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();
    list.add(this.getClass().getName());
    org.apache.thrift.TFieldIdEnum setField = getSetField();
    if (setField != null) {
      list.add(setField.getThriftFieldId());
      Object value = getFieldValue();
      if (value instanceof org.apache.thrift.TEnum) {
        list.add(((org.apache.thrift.TEnum)getFieldValue()).getValue());
      } else {
        list.add(value);
      }
    }
    return list.hashCode();
  }
  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


}
