/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package tp.bigdata.schema;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
public class UserPropertyValue extends org.apache.thrift.TUnion<UserPropertyValue, UserPropertyValue._Fields> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("UserPropertyValue");
  private static final org.apache.thrift.protocol.TField NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("name", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField EMAIL_FIELD_DESC = new org.apache.thrift.protocol.TField("email", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField PHONE_FIELD_DESC = new org.apache.thrift.protocol.TField("phone", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField BIRDTHDAY_FIELD_DESC = new org.apache.thrift.protocol.TField("birdthday", org.apache.thrift.protocol.TType.STRING, (short)4);

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    NAME((short)1, "name"),
    EMAIL((short)2, "email"),
    PHONE((short)3, "phone"),
    BIRDTHDAY((short)4, "birdthday");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // NAME
          return NAME;
        case 2: // EMAIL
          return EMAIL;
        case 3: // PHONE
          return PHONE;
        case 4: // BIRDTHDAY
          return BIRDTHDAY;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.NAME, new org.apache.thrift.meta_data.FieldMetaData("name", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.EMAIL, new org.apache.thrift.meta_data.FieldMetaData("email", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PHONE, new org.apache.thrift.meta_data.FieldMetaData("phone", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.BIRDTHDAY, new org.apache.thrift.meta_data.FieldMetaData("birdthday", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(UserPropertyValue.class, metaDataMap);
  }

  public UserPropertyValue() {
    super();
  }

  public UserPropertyValue(_Fields setField, Object value) {
    super(setField, value);
  }

  public UserPropertyValue(UserPropertyValue other) {
    super(other);
  }
  public UserPropertyValue deepCopy() {
    return new UserPropertyValue(this);
  }

  public static UserPropertyValue name(String value) {
    UserPropertyValue x = new UserPropertyValue();
    x.set_name(value);
    return x;
  }

  public static UserPropertyValue email(String value) {
    UserPropertyValue x = new UserPropertyValue();
    x.set_email(value);
    return x;
  }

  public static UserPropertyValue phone(String value) {
    UserPropertyValue x = new UserPropertyValue();
    x.set_phone(value);
    return x;
  }

  public static UserPropertyValue birdthday(String value) {
    UserPropertyValue x = new UserPropertyValue();
    x.set_birdthday(value);
    return x;
  }


  @Override
  protected void checkType(_Fields setField, Object value) throws ClassCastException {
    switch (setField) {
      case NAME:
        if (value instanceof String) {
          break;
        }
        throw new ClassCastException("Was expecting value of type String for field 'name', but got " + value.getClass().getSimpleName());
      case EMAIL:
        if (value instanceof String) {
          break;
        }
        throw new ClassCastException("Was expecting value of type String for field 'email', but got " + value.getClass().getSimpleName());
      case PHONE:
        if (value instanceof String) {
          break;
        }
        throw new ClassCastException("Was expecting value of type String for field 'phone', but got " + value.getClass().getSimpleName());
      case BIRDTHDAY:
        if (value instanceof String) {
          break;
        }
        throw new ClassCastException("Was expecting value of type String for field 'birdthday', but got " + value.getClass().getSimpleName());
      default:
        throw new IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected Object standardSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TField field) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(field.id);
    if (setField != null) {
      switch (setField) {
        case NAME:
          if (field.type == NAME_FIELD_DESC.type) {
            String name;
            name = iprot.readString();
            return name;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case EMAIL:
          if (field.type == EMAIL_FIELD_DESC.type) {
            String email;
            email = iprot.readString();
            return email;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case PHONE:
          if (field.type == PHONE_FIELD_DESC.type) {
            String phone;
            phone = iprot.readString();
            return phone;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case BIRDTHDAY:
          if (field.type == BIRDTHDAY_FIELD_DESC.type) {
            String birdthday;
            birdthday = iprot.readString();
            return birdthday;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        default:
          throw new IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
      return null;
    }
  }

  @Override
  protected void standardSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case NAME:
        String name = (String)value_;
        oprot.writeString(name);
        return;
      case EMAIL:
        String email = (String)value_;
        oprot.writeString(email);
        return;
      case PHONE:
        String phone = (String)value_;
        oprot.writeString(phone);
        return;
      case BIRDTHDAY:
        String birdthday = (String)value_;
        oprot.writeString(birdthday);
        return;
      default:
        throw new IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected Object tupleSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, short fieldID) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(fieldID);
    if (setField != null) {
      switch (setField) {
        case NAME:
          String name;
          name = iprot.readString();
          return name;
        case EMAIL:
          String email;
          email = iprot.readString();
          return email;
        case PHONE:
          String phone;
          phone = iprot.readString();
          return phone;
        case BIRDTHDAY:
          String birdthday;
          birdthday = iprot.readString();
          return birdthday;
        default:
          throw new IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      throw new TProtocolException("Couldn't find a field with field id " + fieldID);
    }
  }

  @Override
  protected void tupleSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case NAME:
        String name = (String)value_;
        oprot.writeString(name);
        return;
      case EMAIL:
        String email = (String)value_;
        oprot.writeString(email);
        return;
      case PHONE:
        String phone = (String)value_;
        oprot.writeString(phone);
        return;
      case BIRDTHDAY:
        String birdthday = (String)value_;
        oprot.writeString(birdthday);
        return;
      default:
        throw new IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TField getFieldDesc(_Fields setField) {
    switch (setField) {
      case NAME:
        return NAME_FIELD_DESC;
      case EMAIL:
        return EMAIL_FIELD_DESC;
      case PHONE:
        return PHONE_FIELD_DESC;
      case BIRDTHDAY:
        return BIRDTHDAY_FIELD_DESC;
      default:
        throw new IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TStruct getStructDesc() {
    return STRUCT_DESC;
  }

  @Override
  protected _Fields enumForId(short id) {
    return _Fields.findByThriftIdOrThrow(id);
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }


  public String get_name() {
    if (getSetField() == _Fields.NAME) {
      return (String)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'name' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void set_name(String value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.NAME;
    value_ = value;
  }

  public String get_email() {
    if (getSetField() == _Fields.EMAIL) {
      return (String)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'email' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void set_email(String value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.EMAIL;
    value_ = value;
  }

  public String get_phone() {
    if (getSetField() == _Fields.PHONE) {
      return (String)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'phone' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void set_phone(String value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.PHONE;
    value_ = value;
  }

  public String get_birdthday() {
    if (getSetField() == _Fields.BIRDTHDAY) {
      return (String)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'birdthday' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void set_birdthday(String value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.BIRDTHDAY;
    value_ = value;
  }

  public boolean is_set_name() {
    return setField_ == _Fields.NAME;
  }


  public boolean is_set_email() {
    return setField_ == _Fields.EMAIL;
  }


  public boolean is_set_phone() {
    return setField_ == _Fields.PHONE;
  }


  public boolean is_set_birdthday() {
    return setField_ == _Fields.BIRDTHDAY;
  }


  public boolean equals(Object other) {
    if (other instanceof UserPropertyValue) {
      return equals((UserPropertyValue)other);
    } else {
      return false;
    }
  }

  public boolean equals(UserPropertyValue other) {
    return other != null && getSetField() == other.getSetField() && getFieldValue().equals(other.getFieldValue());
  }

  @Override
  public int compareTo(UserPropertyValue other) {
    int lastComparison = org.apache.thrift.TBaseHelper.compareTo(getSetField(), other.getSetField());
    if (lastComparison == 0) {
      return org.apache.thrift.TBaseHelper.compareTo(getFieldValue(), other.getFieldValue());
    }
    return lastComparison;
  }


  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();
    list.add(this.getClass().getName());
    org.apache.thrift.TFieldIdEnum setField = getSetField();
    if (setField != null) {
      list.add(setField.getThriftFieldId());
      Object value = getFieldValue();
      if (value instanceof org.apache.thrift.TEnum) {
        list.add(((org.apache.thrift.TEnum)getFieldValue()).getValue());
      } else {
        list.add(value);
      }
    }
    return list.hashCode();
  }
  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


}
